config/routes.rb
Rails.application.routes.draw do
  root to: 'photos#index'

  resources :users, only: [:create]
  get 'create_account', to: 'users#new', as: :create_account

  resources :user_sessions, only: [:create]
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
  post 'sign_out', to: 'user_sessions#destroy', as: :sign_out

  resources :photos, only: [:index, :create]
  get 'post_photo', to: 'photos#new', as: :post_photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 5 }
  validates :password, confirmation: true
  validates :username, uniqueness: true

  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  def not_authenticated
    redirect_to :sign_in
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = current_user.photos
  end

  def new
    @photo = Photo.new
  end

  def create
    photo = Photo.create(user_id: current_user.id)
    photo.image.attach(params[:photo][:image])
    redirect_to(:root, notice: 'photo uploaded!')
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:username], params[:password])

    if @user
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:sign_in, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_back_or_to(:root, notice: 'Welcome!')
    else
      flash.now[:alert] = @user.errors.full_messages
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="nav">
      <% if current_user %>
        <%= link_to "Post a Photo", :post_photo %>
        <%= link_to "Logout", :sign_out, method: :post %>
      <% else %>
        <%= link_to "Create account", :create_account %> |
        <%= link_to "Sign in", :sign_in %>
      <% end %>
    </div>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<h1>Wow!</h1>
<p>You're an artist!</p>

<% @photos.each do |photo| -%>
  <%= image_tag photo.image %>
<% end %>

app/views/photos/new.html.erb
<h1>Upload a photo</h1>

<%= form_with(model: @photo, local: true) do |form| %>
  <div class="field">
    <%= form.label "New Photo" %>
    <%= form.file_field :image, required: true %>
  </div>
  <div class="actions">
    <%= form.submit "Post Photo" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Sign in!</h1>

<%= form_with url: user_sessions_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Sign in" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Join Finsta!</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, required: true %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>
  <%= form.submit 'Create Account' %>
<% end %>